name: inisite-nf
channels:
  - r
  - bioconda
  - defaults
dependencies:
  - bedtools=2.29.2
  - bowtie=1.2.3
  - fastqc=0.11.9
  - macs2=2.2.6
  - pandas=1.0.5
  - pip=20.0.2
  - pybedtools=0.8.1
  - pysam=0.15.3
  - python=3.7.6
  - r-ggplot2=3.1.1
  - samtools=1.9
  - trim-galore=0.6.5
  - pip:
    - multiqc==1.9
    - rpy2==3.3.5
