name: inisite-nf
channels:
  - r
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _r-mutex=1.0.0
  - bedtools=2.29.2
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - blas=1.0
  - bwidget=1.9.11
  - bzip2=1.0.8
  - ca-certificates=2020.6.24
  - cairo=1.14.12
  - certifi=2020.6.20
  - curl=7.67.0
  - fontconfig=2.13.0
  - freetype=2.10.2
  - fribidi=1.0.9
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib=2.63.1
  - graphite2=1.3.14
  - gsl=2.4
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=1.8.8
  - htslib=1.9
  - icu=58.2
  - intel-openmp=2020.1
  - jpeg=9b
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libcurl=7.67.0
  - libdeflate=1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - macs2=2.2.6
  - make=4.2.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.1
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openssl=1.1.1g
  - pandas=1.0.5
  - pango=1.42.4
  - pcre=8.44
  - pip=20.1.1
  - pixman=0.40.0
  - pybedtools=0.8.1
  - pysam=0.15.3
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2020.1
  - r-assertthat=0.2.1
  - r-base=3.6.1
  - r-cli=1.1.0
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-dichromat=2.0_0
  - r-digest=0.6.18
  - r-fansi=0.4.0
  - r-ggplot2=3.1.1
  - r-glue=1.3.1
  - r-gtable=0.3.0
  - r-labeling=0.3
  - r-lattice=0.20_38
  - r-lazyeval=0.2.2
  - r-magrittr=1.5
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-mgcv=1.8_28
  - r-munsell=0.5.0
  - r-nlme=3.1_139
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.2
  - r-plyr=1.8.4
  - r-r6=2.4.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.1
  - r-reshape2=1.4.3
  - r-rlang=0.3.4
  - r-scales=1.0.0
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-tibble=2.1.1
  - r-utf8=1.1.4
  - r-viridislite=0.3.0
  - r-withr=2.1.2
  - readline=7.0
  - samtools=1.9
  - setuptools=49.2.0
  - six=1.15.0
  - sqlite=3.31.1
  - tk=8.6.10
  - tktable=2.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - attrs==19.3.0
    - cffi==1.14.1
    - importlib-metadata==1.7.0
    - iniconfig==1.0.0
    - jinja2==2.11.2
    - markupsafe==1.1.1
    - more-itertools==8.4.0
    - packaging==20.4
    - pluggy==0.13.1
    - py==1.9.0
    - pycparser==2.20
    - pyparsing==2.4.7
    - pytest==6.0.0
    - rpy2==3.3.5
    - toml==0.10.1
    - tzlocal==2.1
    - zipp==3.1.0
